install:
  - choco install rsync
  - node --version
  - npm --version
  - npm install
  - pip install --user cram
  - bash ./tests/pre-download-elm-packages.sh

build: off

test_script:
  - bash ./tests/make_links.sh
  - cram -v ./tests
